{% set name = "jupyter-black" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter-black-{{ version }}.tar.gz
  sha256: 2a38f33d4c321eb768f426103635ac9b80b40c9e42aa06072a729e3caddca4c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - black >=21
    - ipython >=7
    - python >=3.7
    - tokenize-rt >=4

test:
  imports:
    - jupyter_black
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/n8henrie/jupyter-black
  summary: A simple extension for Jupyter Notebook and Jupyter Lab to beautify Python code automatically using Black. Fork of dnanhkhoa/nb_black.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bryanwweber
