{% set name = "jupyter-black" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter-black-{{ version }}.tar.gz
  sha256: ddc72d9c79515872dc833bef5dbb32f2611679bf92996c1426f339cc87197975

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - black >=21.9b0
    - ipython >=7.27.0
    - python >=3.7
    - tokenize-rt >=4.1.0

test:
  imports:
    - jupyter_black
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/n8henrie/jupyter-black
  summary: A simple extension for Jupyter Notebook and Jupyter Lab to beautify Python code automatically using Black. Fork of dnanhkhoa/nb_black.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bryanwweber
